services:
  client:
    build: ./client
    ports:
      - '5173:5173'
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules/
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - '3000:3000'
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    image: postgres:15.7-alpine
    ports:
      - '5432:5432'
    env_file:
      - path: ./.env
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
